services:
  - type: web
    name: sim-studio
    runtime: docker
    plan: starter
    region: oregon
    branch: main
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_TELEMETRY_DISABLED
        value: "1"
      - key: VERCEL_TELEMETRY_DISABLED
        value: "1"
      - key: PORT
        value: "3000"
      - key: HOSTNAME
        value: "0.0.0.0"
      - key: BETTER_AUTH_SECRET
        generateValue: true
      - key: ENCRYPTION_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: sim-db
          property: connectionString
      - key: NEXT_PUBLIC_APP_URL
        value: https://sim-studio.onrender.com
      - key: BETTER_AUTH_URL
        value: https://sim-studio.onrender.com
      - key: GITHUB_CLIENT_ID
          value: Iv23liF3hNekLu0MnrnC
        - key: GITHUB_CLIENT_SECRET
          value: 728f38292ce2ce5cba5e89a23f34d0ced036e6ac
        - key: GOOGLE_CLIENT_ID
          value: 1099101673529-o8o7ms6qgjii0kcm2he37i16ibv68onk.apps.googleusercontent.com
        - key: GOOGLE_CLIENT_SECRET
          value: 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
    healthCheckPath: /
    
databases:
  - name: sim-db
    databaseName: sim
    user: sim_user
    plan: starter
    region: oregon
    postgresMajorVersion: 15